stages:
  - format
  - lint
  - build
  - test

# Stage: Code formatting with clang-format
format:
  stage: format
  image: archlinux:latest
  script:
    - pacman -Syu --noconfirm  # Update the package list and upgrade system
    - pacman -S --noconfirm cmake clang wxgtk3  # Install the required packages
    - mkdir -p build
    - cd build
    - cmake ..
    - cmake --build . --target format
  allow_failure: true

# Stage: Static analysis with cppcheck
lint:
  stage: lint
  image: gcc:latest
  script:
    - apt-get update && apt-get install -y cmake cppcheck libwxgtk3.2-dev
    - mkdir -p build
    - cd build
    - cmake ..
    - cmake --build . --target check
  allow_failure: true

build:
  stage: build
  image: gcc:latest
  before_script:
    - apt-get update && apt-get install -y cmake libwxgtk3.2-dev
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - cmake --build .
  allow_failure: false

test:
  stage: test
  image: gcc:latest
  before_script:
    - apt-get update && apt-get install -y cmake libwxgtk3.2-dev
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - cmake --build .
    - ctest --output-on-failure
  allow_failure: false
