stages:
  - format
  - lint
  - test

format:
  stage: format
  image: ubuntu:22.04
  script:
    - apt-get update && apt-get install -y clang clang-format cmake git libwxgtk3.0-gtk3-dev
    - mkdir -p build
    - cd build
    - cmake ..
    - cmake --build . --target format
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

lint:
  stage: lint
  image: ubuntu:22.04
  script:
    - apt-get update && apt-get install -y clang cmake cppcheck libwxgtk3.0-gtk3-dev
    - mkdir -p build
    - cd build
    - cmake ..
    - cmake --build . --target check
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

test:
  stage: test
  image: ubuntu:22.04
  script:
    - apt-get update && apt-get install -y clang cmake libwxgtk3.0-gtk-dev
    - mkdir -p build
    - cd build
    - cmake ..
    - cmake --build . -j $(nproc)
    - ctest --output-on-failure
  allow_failure: false
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
