stages:
  - format
  - lint
  - test

format:
  stage: format
  image: archlinux:latest # We use arch linux as the base image because it has a recent version of clang-format
  script:
    - pacman -Syu --noconfirm  # Update the package list and upgrade system
    - pacman -S --noconfirm cmake make git clang wxgtk3  # Install the required packages
    - mkdir -p build
    - cd build
    - cmake ..
    - cmake --build . --target format
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

lint:
  stage: lint
  image: gcc:latest
  script:
    - apt-get update && apt-get install -y cmake cppcheck libwxgtk3.2-dev
    - mkdir -p build
    - cd build
    - cmake ..
    - cmake --build . --target check
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

test:
  stage: test
  image: gcc:latest
  before_script:
    - apt-get update && apt-get install -y cmake libwxgtk3.2-dev
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - cmake --build . -j $(nproc)
    - ctest --output-on-failure
  allow_failure: false
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
